/* ============================================================
   data.js
   Datos simulados de la plataforma "Juntos".
   No hay backend: este archivo hace las veces de base de datos.
   Todas las páginas leen de window.IDEAS_DATA.
   ============================================================ */

/**
 * Estructura de cada idea:
 * {
 *   id: number,
 *   nombre: string,
 *   descripcion: string,
 *   categoria: "parejas" | "amigos",
 *   tipo: string,                 // ver listas de filtro en cada sección
 *   ocasion: string,
 *   presupuesto: "gratis" | "economico" | "medio" | "alto",
 *   duracion: string,             // texto libre, ej. "2 horas"
 *   tiempo: string,               // clave de filtro: "menos-1h" | "1-2h" | "medio-dia" | "todo-el-dia"
 *   dificultad: "facil" | "intermedia" | "dificil",
 *   personas: string | null,      // solo amigos: "2" | "3-5" | "6-10" | "mas-10"
 *   materiales: string[],
 *   instrucciones: string[],
 *   pinterest: string,            // URL real
 *   tiktok: string,               // URL real
 *   instagram: string,            // URL real
 *   estado: "aprobada" | "pendiente" | "rechazada",
 *   autor: string,
 *   fecha: string,                // ISO yyyy-mm-dd (fecha de publicación/envío)
 *   vistas: number                // simula popularidad para "más consultadas"
 * }
 */

window.IDEAS_DATA = [

  // ============ PAREJAS ============

  {
    id: 1,
    nombre: "Caja sorpresa para aniversario",
    descripcion: "Una caja llena de notas, fotos y pequeños detalles que recuerden momentos especiales de la relación.",
    categoria: "parejas",
    tipo: "manualidad",
    ocasion: "aniversario",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Caja de cartón o madera", "Fotos impresas", "Notas escritas a mano", "Cinta y decoración"],
    instrucciones: [
      "Elige una caja que puedan decorar a su gusto.",
      "Reúne fotos y recuerdos importantes de la relación.",
      "Escribe una nota por cada recuerdo, explicando por qué es especial.",
      "Decora la caja por fuera con el tema que más los represente.",
      "Entrégala en un momento tranquilo para que puedan revisarla juntos."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=caja%20sorpresa%20aniversario",
    tiktok: "https://www.tiktok.com/search?q=caja%20sorpresa%20aniversario",
    instagram: "https://www.instagram.com/explore/tags/cajasorpresa/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-04",
    vistas: 482
  },
  {
    id: 2,
    nombre: "Picnic romántico al atardecer",
    descripcion: "Una salida sencilla a un parque o mirador, con snacks, una manta y buena compañía para ver el atardecer.",
    categoria: "parejas",
    tipo: "cita",
    ocasion: "cita",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Manta", "Snacks y bebidas", "Bocina pequeña (opcional)"],
    instrucciones: [
      "Elige un parque o mirador con buena vista al atardecer.",
      "Prepara snacks fáciles de transportar.",
      "Llega con tiempo para instalarse antes de que empiece a caer el sol.",
      "Lleven una lista de música para ambientar el momento."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=picnic%20romantico%20atardecer",
    tiktok: "https://www.tiktok.com/search?q=picnic%20romantico",
    instagram: "https://www.instagram.com/explore/tags/picnicromantico/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-18",
    vistas: 610
  },
  {
    id: 3,
    nombre: "Cena a la luz de las velas en casa",
    descripcion: "Recrea la experiencia de un restaurante elegante sin salir de casa, con un menú sencillo y buena ambientación.",
    categoria: "parejas",
    tipo: "cita",
    ocasion: "san-valentin",
    presupuesto: "medio",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Velas", "Mantel", "Ingredientes para el menú", "Música ambiental"],
    instrucciones: [
      "Elijan juntos un menú de 2 o 3 tiempos.",
      "Preparen la mesa con mantel, velas y vajilla especial.",
      "Cocinen juntos o sorpréndanse turnándose los platos.",
      "Bajen las luces y dejen que la música ambiente la noche."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=cena%20romantica%20en%20casa",
    tiktok: "https://www.tiktok.com/search?q=cena%20romantica%20en%20casa",
    instagram: "https://www.instagram.com/explore/tags/cenaromantica/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-22",
    vistas: 754
  },
  {
    id: 4,
    nombre: "Álbum de fotos hecho a mano",
    descripcion: "Un scrapbook con las fotos y anécdotas más importantes de la relación, ideal para regalar en una fecha especial.",
    categoria: "parejas",
    tipo: "manualidad",
    ocasion: "aniversario",
    presupuesto: "economico",
    duracion: "3 horas",
    tiempo: "medio-dia",
    dificultad: "dificil",
    personas: null,
    materiales: ["Álbum o cuaderno en blanco", "Fotos impresas", "Marcadores y pegamento", "Stickers y washi tape"],
    instrucciones: [
      "Selecciona las fotos más significativas de la relación.",
      "Organízalas por fecha o por tipo de recuerdo.",
      "Decora cada página contando la historia detrás de cada foto.",
      "Agrega una dedicatoria en la última página."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=scrapbook%20pareja",
    tiktok: "https://www.tiktok.com/search?q=scrapbook%20pareja",
    instagram: "https://www.instagram.com/explore/tags/scrapbookpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-09",
    vistas: 331
  },
  {
    id: 5,
    nombre: "Escapada de fin de semana",
    descripcion: "Una salida corta a un destino cercano para desconectarse juntos, sin necesidad de planear un viaje grande.",
    categoria: "parejas",
    tipo: "salida",
    ocasion: "cumpleanos",
    presupuesto: "alto",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "facil",
    personas: null,
    materiales: ["Reserva de hospedaje", "Transporte", "Maleta ligera"],
    instrucciones: [
      "Elijan un destino a máximo 2-3 horas de distancia.",
      "Reserven el hospedaje con anticipación.",
      "Dejen al menos medio día libre sin planes fijos.",
      "Aprovechen para desconectarse del celular el mayor tiempo posible."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=escapada%20de%20fin%20de%20semana%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=escapada%20fin%20de%20semana%20pareja",
    instagram: "https://www.instagram.com/explore/tags/escapadaenpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-05-02",
    vistas: 298
  },
  {
    id: 6,
    nombre: "Carta con frases del inicio de la relación",
    descripcion: "Una carta escrita a mano recordando cómo empezó todo, ideal como detalle simple pero significativo.",
    categoria: "parejas",
    tipo: "detalle",
    ocasion: "dia-especial",
    presupuesto: "gratis",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: null,
    materiales: ["Papel y sobre", "Bolígrafo"],
    instrucciones: [
      "Recuerda los primeros mensajes, citas o momentos importantes.",
      "Escribe la carta como si estuvieras contando esa historia.",
      "Cierra con una frase sobre lo que sientes hoy.",
      "Entrégala en un sobre decorado a mano."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=carta%20de%20amor%20escrita%20a%20mano",
    tiktok: "https://www.tiktok.com/search?q=carta%20de%20amor",
    instagram: "https://www.instagram.com/explore/tags/cartadeamor/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-30",
    vistas: 402
  },
  {
    id: 7,
    nombre: "Clase de cocina en pareja",
    descripcion: "Aprendan juntos a preparar un platillo nuevo, en casa o en una clase presencial, como plan diferente para una cita.",
    categoria: "parejas",
    tipo: "actividad",
    ocasion: "cita",
    presupuesto: "medio",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Ingredientes según la receta", "Delantales (opcional)"],
    instrucciones: [
      "Elijan una receta que ninguno de los dos haya preparado antes.",
      "Compren los ingredientes juntos o repártanse la lista.",
      "Cocinen en equipo, turnándose los pasos.",
      "Disfruten el resultado con una mesa bien puesta."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20cocina%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cocinar%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/cocinarenpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-27",
    vistas: 265
  },
  {
    id: 8,
    nombre: "Flores y nota sorpresa en el trabajo",
    descripcion: "Un pequeño gesto para alegrar el día: enviar o llevar flores con una nota corta, sin necesidad de ocasión especial.",
    categoria: "parejas",
    tipo: "sorpresa",
    ocasion: "sin-ocasion",
    presupuesto: "economico",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: null,
    materiales: ["Ramo pequeño de flores", "Nota corta"],
    instrucciones: [
      "Elige un ramo sencillo, no hace falta que sea grande.",
      "Escribe una nota breve y honesta.",
      "Coordina la entrega para que sea una sorpresa real.",
      "Si no puedes ir en persona, pide ayuda a alguien de confianza para entregarlo."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=sorpresa%20de%20flores%20en%20el%20trabajo",
    tiktok: "https://www.tiktok.com/search?q=sorpresa%20de%20flores",
    instagram: "https://www.instagram.com/explore/tags/sorpresadeflores/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-15",
    vistas: 519
  },
  {
    id: 9,
    nombre: "Noche de juegos de mesa en casa",
    descripcion: "Una noche relajada jugando juegos de mesa o de cartas, ideal para reconectar sin gastar mucho.",
    categoria: "parejas",
    tipo: "cita",
    ocasion: "reconciliacion",
    presupuesto: "gratis",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Juegos de mesa o cartas", "Snacks"],
    instrucciones: [
      "Elijan 2 o 3 juegos que ambos disfruten.",
      "Preparen snacks sencillos para picar mientras juegan.",
      "Dejen el celular a un lado durante ese rato.",
      "Aprovechen para hablar con calma entre partida y partida."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=noche%20de%20juegos%20de%20mesa%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=noche%20de%20juegos%20de%20mesa",
    instagram: "https://www.instagram.com/explore/tags/nochedejuegos/",
    estado: "pendiente",
    autor: "Valentina R.",
    fecha: "2026-07-19",
    vistas: 47
  },
  {
    id: 10,
    nombre: "Sesión de fotos espontánea en la ciudad",
    descripcion: "Un recorrido corto por lugares con buena luz o color, tomándose fotos espontáneas como recuerdo del día.",
    categoria: "parejas",
    tipo: "actividad",
    ocasion: "aniversario",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Celular o cámara", "Ropa cómoda"],
    instrucciones: [
      "Elijan 2 o 3 puntos de la ciudad con buena luz natural.",
      "Vayan a media tarde para aprovechar la luz dorada.",
      "Tómense fotos espontáneas, sin forzar poses.",
      "Elijan juntos sus 5 favoritas para imprimir después."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=sesion%20de%20fotos%20espontanea%20pareja",
    tiktok: "https://www.tiktok.com/search?q=fotos%20espontaneas%20pareja",
    instagram: "https://www.instagram.com/explore/tags/fotosenpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-21",
    vistas: 373
  },

    {
    id: 21,
    nombre: "Clase de pintura en pareja",
    descripcion: "Una clase guiada (o un tutorial en casa) para pintar juntos un mismo cuadro o dos lienzos que combinen entre sí.",
    categoria: "parejas",
    tipo: "actividad",
    ocasion: "cita",
    presupuesto: "medio",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Lienzos", "Pinturas y pinceles", "Ropa que se pueda manchar"],
    instrucciones: [
      "Elijan un tutorial o clase con un estilo que les guste a ambos.",
      "Preparen el espacio para no manchar muebles ni piso.",
      "Pinten a su ritmo, sin buscar la perfección.",
      "Cuelguen el resultado en casa como recuerdo."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20pintura%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=pintar%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/pintarenpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-15",
    vistas: 198
  },
  {
    id: 22,
    nombre: "Regalo personalizado grabado",
    descripcion: "Un objeto con grabado personalizado (llavero, joya, madera) con una fecha o frase importante para los dos.",
    categoria: "parejas",
    tipo: "regalo",
    ocasion: "aniversario",
    presupuesto: "medio",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: null,
    materiales: ["Objeto a grabar", "Frase o fecha elegida"],
    instrucciones: [
      "Elijan un objeto que la otra persona use seguido.",
      "Piensen una frase corta o una fecha con significado.",
      "Busquen un taller o servicio de grabado local.",
      "Entrégalo envuelto con una nota que explique el porqué."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=regalo%20personalizado%20grabado%20pareja",
    tiktok: "https://www.tiktok.com/search?q=regalo%20personalizado%20pareja",
    instagram: "https://www.instagram.com/explore/tags/regalopersonalizado/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-09",
    vistas: 287
  },
  {
    id: 23,
    nombre: "Spa en casa para dos",
    descripcion: "Una tarde de relajación en casa con mascarillas, masajes y ambiente tranquilo, como si fuera un spa de verdad.",
    categoria: "parejas",
    tipo: "detalle",
    ocasion: "san-valentin",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Mascarillas faciales", "Aceite para masaje", "Velas o luces suaves", "Música relajante"],
    instrucciones: [
      "Preparen el espacio con luz baja y música suave.",
      "Empiecen con mascarillas mientras conversan con calma.",
      "Túrnense para darse un masaje corto de manos u hombros.",
      "Cierren con té o infusión caliente."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=spa%20en%20casa%20para%20dos",
    tiktok: "https://www.tiktok.com/search?q=spa%20en%20casa%20pareja",
    instagram: "https://www.instagram.com/explore/tags/spaencasa/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-01",
    vistas: 445
  },
  {
    id: 24,
    nombre: "Búsqueda del tesoro casera",
    descripcion: "Un recorrido de pistas escondidas por la casa o el barrio que termina en una sorpresa o un regalo.",
    categoria: "parejas",
    tipo: "sorpresa",
    ocasion: "aniversario",
    presupuesto: "gratis",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Papeles con pistas", "Un regalo o sorpresa final"],
    instrucciones: [
      "Piensa 5 o 6 pistas conectadas con lugares o recuerdos importantes.",
      "Escóndelas en orden por la casa o el barrio.",
      "Deja la primera pista en un lugar visible para empezar.",
      "Prepara la sorpresa final en el último punto del recorrido."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=busqueda%20del%20tesoro%20para%20pareja",
    tiktok: "https://www.tiktok.com/search?q=busqueda%20del%20tesoro%20pareja",
    instagram: "https://www.instagram.com/explore/tags/busquedadeltesoro/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-27",
    vistas: 312
  },
  {
    id: 25,
    nombre: "Cata de vinos o quesos",
    descripcion: "Una cata guiada (en casa o en un lugar especializado) probando distintas variedades y comparando notas.",
    categoria: "parejas",
    tipo: "salida",
    ocasion: "cita",
    presupuesto: "alto",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Selección de vinos o quesos", "Copas o platos pequeños", "Agua para limpiar el paladar"],
    instrucciones: [
      "Elijan 3 o 4 variedades distintas para comparar.",
      "Sirvan porciones pequeñas de cada una.",
      "Comenten juntos qué les gusta de cada opción.",
      "Anoten sus favoritas para repetir después."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=cata%20de%20vinos%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cata%20de%20vinos%20pareja",
    instagram: "https://www.instagram.com/explore/tags/catadevinos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-05-19",
    vistas: 256
  },
  {
    id: 26,
    nombre: "Mensajes ocultos por la casa",
    descripcion: "Notas cortas con mensajes lindos escondidas en lugares cotidianos, para que la otra persona las vaya encontrando durante el día.",
    categoria: "parejas",
    tipo: "detalle",
    ocasion: "dia-especial",
    presupuesto: "gratis",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: null,
    materiales: ["Notas adhesivas", "Bolígrafo"],
    instrucciones: [
      "Escribe entre 5 y 8 notas cortas y sinceras.",
      "Escóndelas en lugares que la persona use ese día (billetera, espejo, taza).",
      "No avises que lo hiciste, deja que las vaya encontrando.",
      "Guarda una última nota para el final del día."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=notas%20sorpresa%20para%20pareja",
    tiktok: "https://www.tiktok.com/search?q=notas%20sorpresa%20pareja",
    instagram: "https://www.instagram.com/explore/tags/notasorpresa/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-08",
    vistas: 389
  },
  {
    id: 27,
    nombre: "Velas aromáticas caseras",
    descripcion: "Una manualidad tranquila para hacer sus propias velas con aromas y colores elegidos entre los dos.",
    categoria: "parejas",
    tipo: "manualidad",
    ocasion: "sin-ocasion",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Cera de soja", "Mechas", "Esencias aromáticas", "Frascos o moldes"],
    instrucciones: [
      "Derritan la cera a baño maría.",
      "Agreguen la esencia elegida y mezclen bien.",
      "Coloquen la mecha centrada en el molde antes de verter.",
      "Dejen enfriar varias horas antes de usarlas."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=velas%20aromaticas%20caseras%20pareja",
    tiktok: "https://www.tiktok.com/search?q=velas%20aromaticas%20caseras",
    instagram: "https://www.instagram.com/explore/tags/velascaseras/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-11",
    vistas: 221
  },
  {
    id: 28,
    nombre: "Cine bajo las estrellas en el patio",
    descripcion: "Una función de cine improvisada en el patio o terraza, con proyector o laptop, mantas y palomitas.",
    categoria: "parejas",
    tipo: "cita",
    ocasion: "reconciliacion",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: null,
    materiales: ["Proyector o laptop", "Mantas y cojines", "Palomitas y snacks"],
    instrucciones: [
      "Elijan una película que ninguno haya visto antes.",
      "Armen el espacio afuera con mantas y buena vista a la pantalla.",
      "Preparen palomitas y snacks antes de empezar.",
      "Aprovechen el ambiente relajado para hablar antes o después."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=cine%20al%20aire%20libre%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cine%20en%20el%20patio",
    instagram: "https://www.instagram.com/explore/tags/cinealairelibre/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-03",
    vistas: 334
  },
  {
    id: 29,
    nombre: "Renovación de votos simbólica",
    descripcion: "Una ceremonia sencilla y privada donde se repiten promesas o se escriben nuevas, como forma de celebrar el tiempo juntos.",
    categoria: "parejas",
    tipo: "sorpresa",
    ocasion: "aniversario",
    presupuesto: "alto",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "dificil",
    personas: null,
    materiales: ["Lugar especial elegido", "Votos escritos", "Algo simbólico para intercambiar"],
    instrucciones: [
      "Elijan un lugar con significado para los dos.",
      "Escriban cada uno sus propios votos o promesas en privado.",
      "Organicen un momento íntimo, sin necesidad de invitados.",
      "Cierren el día con una cena o celebración tranquila."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=renovacion%20de%20votos%20simbolica",
    tiktok: "https://www.tiktok.com/search?q=renovacion%20de%20votos",
    instagram: "https://www.instagram.com/explore/tags/renovaciondevotos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-06-14",
    vistas: 167
  },
  {
    id: 30,
    nombre: "Clase de baile de salón",
    descripcion: "Una clase de salsa, bachata o tango para aprender juntos un baile nuevo, presencial o siguiendo un tutorial.",
    categoria: "parejas",
    tipo: "actividad",
    ocasion: "san-valentin",
    presupuesto: "medio",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "intermedia",
    personas: null,
    materiales: ["Espacio despejado", "Ropa cómoda", "Lista de canciones"],
    instrucciones: [
      "Elijan el estilo de baile que más les llame la atención.",
      "Reserven una clase o sigan un tutorial paso a paso.",
      "Practiquen los pasos básicos varias veces antes de combinarlos.",
      "Terminen bailando una canción completa ya sin pausas."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20baile%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=baile%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/bailenpareja/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-13",
    vistas: 298
  },
  {
    id: 41,
    nombre: "Ruta de miradores al atardecer",
    descripcion: "Un recorrido corto por dos o tres miradores de la ciudad, cronometrado para llegar al último justo con la puesta de sol.",
    categoria: "parejas", tipo: "salida", ocasion: "cita", presupuesto: "gratis",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: null,
    materiales: ["Transporte", "Celular o cámara"],
    instrucciones: ["Elijan 2 o 3 miradores accesibles en un mismo trayecto.", "Calculen los tiempos para llegar al mejor mirador antes del atardecer.", "Lleven algo abrigado si refresca al caer la noche.", "Tómense una foto juntos en cada parada."],
    pinterest: "https://www.pinterest.com/search/pins/?q=miradores%20al%20atardecer%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=miradores%20al%20atardecer",
    instagram: "https://www.instagram.com/explore/tags/miradoratardecer/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-11", vistas: 214
  },
  {
    id: 42,
    nombre: "Intercambio de cartas por correo postal",
    descripcion: "Escribirse cartas de verdad y enviarlas por correo, aunque vivan juntos, para revivir la emoción de recibir algo físico.",
    categoria: "parejas", tipo: "detalle", ocasion: "aniversario", presupuesto: "economico",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Papel y sobres", "Estampillas"],
    instrucciones: ["Escriban cada uno una carta sin mostrársela al otro.", "Envíenla por correo a su propia dirección.", "Esperen juntos a que lleguen los sobres.", "Léanlas en voz alta cuando lleguen."],
    pinterest: "https://www.pinterest.com/search/pins/?q=cartas%20por%20correo%20para%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cartas%20por%20correo%20pareja",
    instagram: "https://www.instagram.com/explore/tags/cartasporcorreo/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-02", vistas: 176
  },
  {
    id: 43,
    nombre: "Maratón de anime o series",
    descripcion: "Un día completo dedicado a avanzar una serie o anime que ambos quieran ver, con pausas para comer algo distinto en cada tramo.",
    categoria: "parejas", tipo: "cita", ocasion: "sin-ocasion", presupuesto: "gratis",
    duracion: "todo el día", tiempo: "todo-el-dia", dificultad: "facil", personas: null,
    materiales: ["Lista de episodios", "Snacks variados"],
    instrucciones: ["Elijan la serie juntos antes de empezar.", "Dividan el día en bloques con descansos.", "Cambien de snack en cada bloque para variar.", "Comenten sus teorías o momentos favoritos entre episodios."],
    pinterest: "https://www.pinterest.com/search/pins/?q=maraton%20de%20series%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=maraton%20de%20series%20pareja",
    instagram: "https://www.instagram.com/explore/tags/maratondeseries/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-20", vistas: 267
  },
  {
    id: 44,
    nombre: "Taller de cerámica en pareja",
    descripcion: "Una clase de torno o modelado a mano donde cada uno crea una pieza, o hacen una entre los dos.",
    categoria: "parejas", tipo: "manualidad", ocasion: "cita", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: null,
    materiales: ["Reserva del taller", "Delantal (lo suele dar el taller)"],
    instrucciones: ["Busquen un taller de cerámica con clases para principiantes.", "Reserven un horario que les acomode a ambos.", "Dejen que el instructor los guíe en las bases.", "Recojan las piezas cocidas unos días después."],
    pinterest: "https://www.pinterest.com/search/pins/?q=taller%20de%20ceramica%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=ceramica%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/ceramicaenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-06", vistas: 189
  },
  {
    id: 45,
    nombre: "Cena sorpresa en un restaurante nuevo",
    descripcion: "Sorprender a la pareja llevándola a un restaurante que no conoce, sin decirle antes a dónde van.",
    categoria: "parejas", tipo: "salida", ocasion: "san-valentin", presupuesto: "alto",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: null,
    materiales: ["Reserva previa", "Transporte"],
    instrucciones: ["Elige un restaurante que sepas que le gustará, sin avisarle.", "Reserva con anticipación, sobre todo en fecha especial.", "Pide que se vista sin decirle el destino.", "Disfruten la sorpresa al llegar."],
    pinterest: "https://www.pinterest.com/search/pins/?q=cena%20sorpresa%20restaurante%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cena%20sorpresa%20pareja",
    instagram: "https://www.instagram.com/explore/tags/cenasorpresa/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-25", vistas: 356
  },
  {
    id: 46,
    nombre: "Álbum digital compartido del año",
    descripcion: "Armar juntos un álbum digital con las mejores fotos del año, para repasar los momentos vividos.",
    categoria: "parejas", tipo: "manualidad", ocasion: "aniversario", presupuesto: "gratis",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Fotos del celular", "App o carpeta compartida"],
    instrucciones: ["Revisen juntos las fotos del último año.", "Elijan las 20 o 30 más significativas.", "Organícenlas por mes o por evento.", "Guárdenlas en un álbum o carpeta compartida."],
    pinterest: "https://www.pinterest.com/search/pins/?q=album%20digital%20del%20a%C3%B1o%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=album%20digital%20pareja",
    instagram: "https://www.instagram.com/explore/tags/albumdelanio/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-05-30", vistas: 143
  },
  {
    id: 47,
    nombre: "Masaje relajante a domicilio",
    descripcion: "Contratar a un masajista a domicilio para una sesión de relajación en pareja, o darse masajes mutuamente con una guía.",
    categoria: "parejas", tipo: "detalle", ocasion: "reconciliacion", presupuesto: "alto",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Aceite para masaje", "Música relajante", "Toallas"],
    instrucciones: ["Preparen un espacio tranquilo en casa.", "Contraten un servicio a domicilio o guíense con un video.", "Bajen las luces y pongan música suave.", "Terminen con una infusión relajante juntos."],
    pinterest: "https://www.pinterest.com/search/pins/?q=masaje%20relajante%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=masaje%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/masajeenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-19", vistas: 198
  },
  {
    id: 48,
    nombre: "Caminata nocturna bajo las estrellas",
    descripcion: "Un paseo tranquilo de noche por un lugar con poca luz artificial, ideal para conversar y ver las estrellas.",
    categoria: "parejas", tipo: "actividad", ocasion: "cita", presupuesto: "gratis",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Ropa abrigada", "Linterna"],
    instrucciones: ["Elijan un lugar seguro y con poca contaminación lumínica.", "Salgan después del anochecer.", "Lleven algo abrigado por si refresca.", "Aprovechen para hablar con calma durante el camino."],
    pinterest: "https://www.pinterest.com/search/pins/?q=caminata%20nocturna%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=caminata%20nocturna%20pareja",
    instagram: "https://www.instagram.com/explore/tags/caminatanocturna/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-08", vistas: 231
  },
  {
    id: 49,
    nombre: "Cupones de citas sorpresa",
    descripcion: "Un set de cupones caseros, cada uno canjeable por una cita o gesto distinto, para usar durante el año.",
    categoria: "parejas", tipo: "regalo", ocasion: "aniversario", presupuesto: "gratis",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Cartulina o papel", "Marcadores", "Tijeras"],
    instrucciones: ["Piensen 8 a 10 citas o gestos distintos.", "Escriban cada uno en un cupón individual.", "Decórenlos y until en un sobre o cajita.", "Canjeen uno cada vez que quieran un plan sorpresa."],
    pinterest: "https://www.pinterest.com/search/pins/?q=cupones%20de%20citas%20para%20pareja",
    tiktok: "https://www.tiktok.com/search?q=cupones%20de%20citas",
    instagram: "https://www.instagram.com/explore/tags/cuponesdecitas/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-05", vistas: 289
  },
  {
    id: 50,
    nombre: "Clase de yoga en pareja",
    descripcion: "Una sesión de yoga para dos, presencial o guiada por video, con posturas pensadas para hacer en equipo.",
    categoria: "parejas", tipo: "actividad", ocasion: "dia-especial", presupuesto: "medio",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "intermedia", personas: null,
    materiales: ["Mat de yoga", "Ropa cómoda"],
    instrucciones: ["Busquen una clase o video de yoga en pareja.", "Despejen un espacio suficiente para ambos.", "Sigan las posturas sin forzar el cuerpo.", "Terminen con una relajación final juntos."],
    pinterest: "https://www.pinterest.com/search/pins/?q=yoga%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=yoga%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/yogaenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-14", vistas: 205
  },
  {
    id: 51,
    nombre: "Fiesta de disfraces solo para dos",
    descripcion: "Una noche temática en casa donde ambos se disfrazan según un tema elegido, con decoración y hasta menú a tono.",
    categoria: "parejas", tipo: "sorpresa", ocasion: "cumpleanos", presupuesto: "economico",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: null,
    materiales: ["Disfraces caseros", "Decoración temática"],
    instrucciones: ["Elijan un tema que a ambos les guste.", "Arme cada uno su disfraz con lo que tengan en casa.", "Decoren un rincón de la casa a tono con el tema.", "Tómense fotos como recuerdo de la noche."],
    pinterest: "https://www.pinterest.com/search/pins/?q=fiesta%20de%20disfraces%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=fiesta%20de%20disfraces%20pareja",
    instagram: "https://www.instagram.com/explore/tags/disfracesenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-06-11", vistas: 158
  },
  {
    id: 52,
    nombre: "Recrear la primera cita",
    descripcion: "Volver al mismo lugar de la primera cita, o recrear lo más posible ese día, como forma de recordar cómo empezó todo.",
    categoria: "parejas", tipo: "cita", ocasion: "aniversario", presupuesto: "economico",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: null,
    materiales: ["Fotos o recuerdos de la primera cita (opcional)"],
    instrucciones: ["Recuerden juntos los detalles de su primera cita.", "Vuelvan al mismo lugar si todavía existe.", "Pidan lo mismo que pidieron esa vez, si lo recuerdan.", "Comparen cómo se sienten hoy respecto a ese día."],
    pinterest: "https://www.pinterest.com/search/pins/?q=recrear%20la%20primera%20cita",
    tiktok: "https://www.tiktok.com/search?q=recrear%20primera%20cita",
    instagram: "https://www.instagram.com/explore/tags/primeracita/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-24", vistas: 312
  },
  {
    id: 53,
    nombre: "Huerto en macetas para dos",
    descripcion: "Armar un pequeño huerto o jardín de hierbas en macetas, para cuidar juntos con el paso de las semanas.",
    categoria: "parejas", tipo: "manualidad", ocasion: "sin-ocasion", presupuesto: "economico",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: null,
    materiales: ["Macetas", "Tierra", "Semillas o plantines"],
    instrucciones: ["Elijan juntos qué plantas o hierbas sembrar.", "Preparen las macetas con tierra y buen drenaje.", "Siembren y rieguen siguiendo las indicaciones de cada planta.", "Turnense el cuidado semana a semana."],
    pinterest: "https://www.pinterest.com/search/pins/?q=huerto%20en%20macetas%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=huerto%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/huertoenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-07", vistas: 167
  },
  {
    id: 54,
    nombre: "Carrera de karts",
    descripcion: "Una tarde competitiva en una pista de karts, para reírse compitiendo el uno contra el otro.",
    categoria: "parejas", tipo: "actividad", ocasion: "cumpleanos", presupuesto: "medio",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Reserva de la pista", "Ropa cómoda"],
    instrucciones: ["Reserven turno en una pista de karts cercana.", "Hagan varias vueltas de práctica antes de competir en serio.", "Definan un pequeño premio para quien gane.", "Celebren juntos al final, gane quien gane."],
    pinterest: "https://www.pinterest.com/search/pins/?q=karts%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=carrera%20de%20karts%20pareja",
    instagram: "https://www.instagram.com/explore/tags/kartsenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-05-16", vistas: 178
  },
  {
    id: 55,
    nombre: "Sesión de karaoke privado",
    descripcion: "Reservar una sala de karaoke privada para cantar juntos sin público, ideal para una noche diferente.",
    categoria: "parejas", tipo: "cita", ocasion: "san-valentin", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: null,
    materiales: ["Reserva de la sala", "Lista de canciones favoritas"],
    instrucciones: ["Reserven una sala de karaoke privado.", "Armen una lista con sus canciones favoritas.", "Canten por turnos o a dúo.", "Pidan algo de comer para acompañar la noche."],
    pinterest: "https://www.pinterest.com/search/pins/?q=karaoke%20privado%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=karaoke%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/karaokeenpareja/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-29", vistas: 224
  },
  {
    id: 56,
    nombre: "Regalo de suscripción sorpresa",
    descripcion: "Regalar una suscripción a algo que a la pareja le guste: streaming, club de libros, café de especialidad, etc.",
    categoria: "parejas", tipo: "regalo", ocasion: "aniversario", presupuesto: "medio",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Tarjeta o comprobante de la suscripción"],
    instrucciones: ["Piensa en un interés o hobby de tu pareja.", "Busca una suscripción relacionada a ese interés.", "Actívala o compra el primer mes/envío.", "Entrégasela con una nota explicando por qué la elegiste."],
    pinterest: "https://www.pinterest.com/search/pins/?q=regalo%20de%20suscripcion%20para%20pareja",
    tiktok: "https://www.tiktok.com/search?q=regalo%20de%20suscripcion",
    instagram: "https://www.instagram.com/explore/tags/regalodesuscripcion/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-16", vistas: 192
  },
  {
    id: 57,
    nombre: "Excursión a un spa termal",
    descripcion: "Una salida de día completo a aguas termales o un spa al aire libre, para desconectarse juntos del todo.",
    categoria: "parejas", tipo: "salida", ocasion: "reconciliacion", presupuesto: "alto",
    duracion: "todo el día", tiempo: "todo-el-dia", dificultad: "facil", personas: null,
    materiales: ["Traje de baño", "Toalla", "Entrada o reserva"],
    instrucciones: ["Busquen un spa termal accesible desde su ciudad.", "Reserven con anticipación si hace falta.", "Dejen el celular guardado la mayor parte del día.", "Aprovechen para hablar con calma entre piscina y piscina."],
    pinterest: "https://www.pinterest.com/search/pins/?q=spa%20termal%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=aguas%20termales%20en%20pareja",
    instagram: "https://www.instagram.com/explore/tags/spatermal/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-18", vistas: 246
  },
  {
    id: 58,
    nombre: "Terrario en frasco",
    descripcion: "Una manualidad tranquila para armar un pequeño terrario dentro de un frasco de vidrio, como decoración para la casa.",
    categoria: "parejas", tipo: "manualidad", ocasion: "sin-ocasion", presupuesto: "economico",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "intermedia", personas: null,
    materiales: ["Frasco de vidrio", "Tierra y piedras pequeñas", "Plantas pequeñas o musgo"],
    instrucciones: ["Coloquen una capa de piedras en el fondo del frasco.", "Agreguen tierra y acomoden las plantas pequeñas.", "Decoren con musgo o piedras decorativas.", "Riéguenlo con moderación cada cierto tiempo."],
    pinterest: "https://www.pinterest.com/search/pins/?q=terrario%20en%20frasco%20pareja",
    tiktok: "https://www.tiktok.com/search?q=terrario%20en%20frasco",
    instagram: "https://www.instagram.com/explore/tags/terrarioenfrasco/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-24", vistas: 149
  },
  {
    id: 59,
    nombre: "Cena de aniversario con menú sorpresa",
    descripcion: "Cada uno prepara en secreto un plato para el otro, y se turnan para revelarlos como un menú sorpresa de aniversario.",
    categoria: "parejas", tipo: "cita", ocasion: "aniversario", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: null,
    materiales: ["Ingredientes según cada plato", "Mantel y vajilla especial"],
    instrucciones: ["Cada uno elige un plato en secreto para sorprender al otro.", "Cocinen por separado, sin mostrar el resultado antes de tiempo.", "Sirvan los platos por turnos, como un menú de varios tiempos.", "Cierren la noche comentando cuál les sorprendió más."],
    pinterest: "https://www.pinterest.com/search/pins/?q=menu%20sorpresa%20de%20aniversario",
    tiktok: "https://www.tiktok.com/search?q=cena%20sorpresa%20aniversario",
    instagram: "https://www.instagram.com/explore/tags/menusorpresa/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-05-03", vistas: 203
  },
  {
    id: 60,
    nombre: "Carta para abrir en el futuro",
    descripcion: "Escribir juntos una carta o grabar un video para abrir/ver dentro de 1 o 5 años, como cápsula del tiempo de la relación.",
    categoria: "parejas", tipo: "detalle", ocasion: "dia-especial", presupuesto: "gratis",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: null,
    materiales: ["Papel y sobre, o celular para grabar", "Caja o lugar para guardarlo"],
    instrucciones: ["Escriban o graben juntos un mensaje para su 'yo futuro'.", "Incluyan cómo se sienten y qué esperan para adelante.", "Sellen la carta o guarden el video con una fecha para abrirlo.", "Guárdenlo en un lugar que no vayan a olvidar."],
    pinterest: "https://www.pinterest.com/search/pins/?q=carta%20para%20el%20futuro%20en%20pareja",
    tiktok: "https://www.tiktok.com/search?q=carta%20al%20futuro%20pareja",
    instagram: "https://www.instagram.com/explore/tags/cartaparaelfuturo/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-06-20", vistas: 134
  },

  

  // ============ AMIGOS ============

  {
    id: 11,
    nombre: "Noche de trivia en casa",
    descripcion: "Organiza una trivia casera con categorías elegidas por el grupo, ideal para una reunión sin gastar de más.",
    categoria: "amigos",
    tipo: "juego",
    ocasion: "reunion",
    presupuesto: "gratis",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Preguntas preparadas o app de trivia", "Papel y lápiz", "Snacks"],
    instrucciones: [
      "Definan las categorías de preguntas entre todos.",
      "Formen equipos de 2 personas.",
      "Lleven el puntaje en una hoja visible.",
      "El equipo ganador elige el snack de la próxima reunión."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=noche%20de%20trivia%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=noche%20de%20trivia",
    instagram: "https://www.instagram.com/explore/tags/nochedetrivia/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-11",
    vistas: 288
  },
  {
    id: 12,
    nombre: "Torneo de videojuegos",
    descripcion: "Un torneo casero con el juego favorito del grupo, con eliminatorias y un pequeño premio simbólico.",
    categoria: "amigos",
    tipo: "juego",
    ocasion: "celebracion",
    presupuesto: "economico",
    duracion: "3 horas",
    tiempo: "medio-dia",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Consola o PC", "Controles adicionales", "Snacks y bebidas"],
    instrucciones: [
      "Elijan el juego y el formato del torneo (eliminación directa o puntos).",
      "Armen un cuadro con los enfrentamientos.",
      "Definan un premio simbólico para el ganador.",
      "Jueguen las rondas con tiempo límite por partida."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20de%20videojuegos%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=torneo%20de%20videojuegos",
    instagram: "https://www.instagram.com/explore/tags/torneogamer/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-08",
    vistas: 356
  },
  {
    id: 13,
    nombre: "Ruta de food trucks",
    descripcion: "Un recorrido por distintos puestos de comida callejera o food trucks de la ciudad, probando un poco de cada uno.",
    categoria: "amigos",
    tipo: "plan-economico",
    ocasion: "dia-especial",
    presupuesto: "economico",
    duracion: "medio día",
    tiempo: "medio-dia",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Efectivo o tarjeta", "Ropa cómoda para caminar"],
    instrucciones: [
      "Investiguen 3 o 4 puestos con buenas reseñas.",
      "Definan una ruta a pie o en transporte entre ellos.",
      "Pidan porciones pequeñas para poder probar de todo.",
      "Terminen el recorrido con un postre en el último punto."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=ruta%20de%20food%20trucks",
    tiktok: "https://www.tiktok.com/search?q=food%20trucks%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/foodtrucks/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-05-14",
    vistas: 214
  },
  {
    id: 14,
    nombre: "Escape room",
    descripcion: "Reserven una sala de escape temática y pongan a prueba al grupo resolviendo acertijos contra el reloj.",
    categoria: "amigos",
    tipo: "actividad",
    ocasion: "celebracion",
    presupuesto: "medio",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "intermedia",
    personas: "3-5",
    materiales: ["Reserva previa", "Grupo de 3 a 6 personas"],
    instrucciones: [
      "Elijan una sala según el tema que más les llame la atención.",
      "Reserven con anticipación, sobre todo en fin de semana.",
      "Lleguen 15 minutos antes para las indicaciones.",
      "Comuníquense bien dentro de la sala: cada pista cuenta."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=escape%20room%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=escape%20room",
    instagram: "https://www.instagram.com/explore/tags/escaperoom/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-27",
    vistas: 447
  },
  {
    id: 15,
    nombre: "Asado o parrillada en el patio",
    descripcion: "Una reunión clásica de grupo grande, con comida a la parrilla, música y juegos al aire libre.",
    categoria: "amigos",
    tipo: "reunion",
    ocasion: "cumpleanos",
    presupuesto: "medio",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Carne y acompañamientos", "Parrilla y carbón", "Bocina para música"],
    instrucciones: [
      "Repartan la lista de compras entre todos.",
      "Preparen la parrilla con anticipación.",
      "Organicen algún juego de patio para antes o después de comer.",
      "Dejen a alguien encargado de la música durante el día."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=asado%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=parrillada%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/asadoconamigos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-06-02",
    vistas: 392
  },
  {
    id: 16,
    nombre: "Maratón de películas con snacks",
    descripcion: "Un plan tranquilo en casa para ver varias películas seguidas, con snacks y pijama incluida.",
    categoria: "amigos",
    tipo: "reunion",
    ocasion: "sin-ocasion",
    presupuesto: "gratis",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Snacks variados", "Mantas y cojines", "Lista de películas"],
    instrucciones: [
      "Elijan juntos las películas antes de empezar.",
      "Preparen el espacio con mantas y cojines suficientes.",
      "Dejen listos los snacks para no interrumpir tanto.",
      "Hagan una pausa entre película y película para estirar las piernas."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=maraton%20de%20peliculas%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=maraton%20de%20peliculas",
    instagram: "https://www.instagram.com/explore/tags/maratondepeliculas/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-05",
    vistas: 501
  },
  {
    id: 17,
    nombre: "Caminata a un mirador",
    descripcion: "Una salida activa en grupo hacia un mirador o sendero cercano, ideal para conversar y desconectarse un rato.",
    categoria: "amigos",
    tipo: "salida",
    ocasion: "dia-especial",
    presupuesto: "gratis",
    duracion: "medio día",
    tiempo: "medio-dia",
    dificultad: "intermedia",
    personas: "6-10",
    materiales: ["Agua y snacks", "Zapatos cómodos", "Protector solar"],
    instrucciones: [
      "Elijan un sendero apto para el nivel del grupo.",
      "Salgan temprano para evitar el calor fuerte.",
      "Lleven suficiente agua para todos.",
      "Aprovechen el mirador para tomarse fotos grupales."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=caminata%20a%20un%20mirador%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=caminata%20mirador",
    instagram: "https://www.instagram.com/explore/tags/caminataamigos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-30",
    vistas: 176
  },
  {
    id: 18,
    nombre: "Clase grupal de baile",
    descripcion: "Una clase de baile en grupo, presencial o improvisada en casa, como plan diferente y activo para el grupo.",
    categoria: "amigos",
    tipo: "actividad",
    ocasion: "celebracion",
    presupuesto: "economico",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "intermedia",
    personas: "mas-10",
    materiales: ["Espacio amplio", "Bocina", "Ropa cómoda"],
    instrucciones: [
      "Elijan el estilo de baile que más les llame la atención.",
      "Consigan un espacio con suficiente lugar para moverse.",
      "Sigan un tutorial o contraten a un instructor por una sesión.",
      "Terminen con un pequeño 'show' grupal de lo aprendido."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20baile%20grupal",
    tiktok: "https://www.tiktok.com/search?q=clase%20de%20baile%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/clasedebaile/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-22",
    vistas: 239
  },
  {
    id: 19,
    nombre: "Regalo grupal para el cumpleañero",
    descripcion: "En vez de varios regalos pequeños, el grupo se organiza para dar un solo regalo especial entre todos.",
    categoria: "amigos",
    tipo: "regalo",
    ocasion: "cumpleanos",
    presupuesto: "medio",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Fondo grupal", "Lista de ideas de regalo"],
    instrucciones: [
      "Abran un fondo común entre los interesados.",
      "Propongan 2 o 3 opciones de regalo y voten.",
      "Designen a una persona para comprarlo y envolverlo.",
      "Acompañen el regalo con una tarjeta firmada por todos."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=regalo%20grupal%20de%20cumpleanos",
    tiktok: "https://www.tiktok.com/search?q=regalo%20grupal%20cumpleanos",
    instagram: "https://www.instagram.com/explore/tags/regalogrupal/",
    estado: "pendiente",
    autor: "Carlos M.",
    fecha: "2026-07-25",
    vistas: 31
  },
  {
    id: 20,
    nombre: "Karaoke en casa",
    descripcion: "Una noche de karaoke casero con lista de canciones armada entre todos, sin necesidad de salir.",
    categoria: "amigos",
    tipo: "experiencia",
    ocasion: "sin-ocasion",
    presupuesto: "economico",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Micrófono o app de karaoke", "Bocina", "Lista de canciones"],
    instrucciones: [
      "Armen la lista de canciones entre todos antes de empezar.",
      "Definan el orden de participación o háganlo libre.",
      "Puntúen las presentaciones si quieren darle un toque de competencia.",
      "Cierren la noche con una canción grupal."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=karaoke%20con%20amigos%20en%20casa",
    tiktok: "https://www.tiktok.com/search?q=karaoke%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/karaokeconamigos/",
    estado: "rechazada",
    autor: "Andrés P.",
    fecha: "2026-06-30",
    vistas: 12
  }
   {
    id: 31,
    nombre: "Noche de comida internacional",
    descripcion: "Cada quien lleva o cocina un platillo de un país distinto, y entre todos arman un menú alrededor del mundo.",
    categoria: "amigos",
    tipo: "reunion",
    ocasion: "reunion",
    presupuesto: "economico",
    duracion: "medio día",
    tiempo: "medio-dia",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Un platillo por persona", "Platos y utensilios suficientes"],
    instrucciones: [
      "Repartan los países o regiones entre los asistentes.",
      "Cada quien prepara o compra su platillo asignado.",
      "Organicen la mesa como un buffet para probar de todo.",
      "Voten juntos cuál fue el platillo favorito de la noche."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=noche%20de%20comida%20internacional%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=noche%20de%20comida%20internacional",
    instagram: "https://www.instagram.com/explore/tags/comidainternacional/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-01-19",
    vistas: 276
  },
  {
    id: 32,
    nombre: "Torneo de bolos",
    descripcion: "Una tarde de bolos entre amigos, con equipos y un pequeño premio simbólico para el que gane.",
    categoria: "amigos",
    tipo: "actividad",
    ocasion: "celebracion",
    presupuesto: "medio",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Reserva de pistas", "Calzado adecuado (se alquila en el lugar)"],
    instrucciones: [
      "Reserven las pistas con anticipación, sobre todo en fin de semana.",
      "Formen equipos parejos entre todos los asistentes.",
      "Jueguen 2 o 3 rondas llevando el marcador.",
      "Definan un premio simbólico para el equipo ganador."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20de%20bolos%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=bolos%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/bolosconamigos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-22",
    vistas: 203
  },
  {
    id: 33,
    nombre: "Camping de fin de semana",
    descripcion: "Una escapada grupal a acampar cerca de la ciudad, con fogata, comida al aire libre y desconexión total.",
    categoria: "amigos",
    tipo: "salida",
    ocasion: "dia-especial",
    presupuesto: "alto",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "intermedia",
    personas: "6-10",
    materiales: ["Carpas y sacos de dormir", "Comida y agua", "Leña para la fogata", "Linternas"],
    instrucciones: [
      "Elijan un sitio de camping seguro y accesible para el grupo.",
      "Repartan qué lleva cada quien (comida, carpas, leña).",
      "Armen el campamento con tiempo antes de que oscurezca.",
      "Cierren la noche alrededor de la fogata."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=camping%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=camping%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/campingconamigos/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-05-08",
    vistas: 312
  },
  {
    id: 34,
    nombre: "Juego de rol de mesa casero",
    descripcion: "Una sesión de un juego de rol (tipo Dungeons & Dragons) con un narrador del grupo guiando la aventura.",
    categoria: "amigos",
    tipo: "juego",
    ocasion: "reunion",
    presupuesto: "gratis",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "intermedia",
    personas: "3-5",
    materiales: ["Manual básico o guía online", "Dados", "Hojas de personaje", "Snacks"],
    instrucciones: [
      "Elijan quién narrará la aventura y quiénes serán jugadores.",
      "Cada jugador arma su personaje antes de empezar.",
      "Jueguen por rondas, dejando espacio para que todos participen.",
      "Guarden el avance de la historia para continuar otro día."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=juego%20de%20rol%20de%20mesa%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=juego%20de%20rol%20de%20mesa",
    instagram: "https://www.instagram.com/explore/tags/juegoderol/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-16",
    vistas: 189
  },
  {
    id: 35,
    nombre: "Voluntariado grupal",
    descripcion: "Dedicar un día a apoyar una causa juntos, como una jornada de limpieza, un albergue o una colecta.",
    categoria: "amigos",
    tipo: "experiencia",
    ocasion: "dia-especial",
    presupuesto: "gratis",
    duracion: "medio día",
    tiempo: "medio-dia",
    dificultad: "facil",
    personas: "mas-10",
    materiales: ["Ropa cómoda", "Agua y snacks", "Contacto con la organización"],
    instrucciones: [
      "Busquen una organización o causa que les interese al grupo.",
      "Coordinen fecha y horario con anticipación.",
      "Lleven agua y ropa adecuada para la actividad.",
      "Cierren el día compartiendo cómo se sintieron con la experiencia."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=voluntariado%20en%20grupo%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=voluntariado%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/voluntariado/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-11",
    vistas: 154
  },
  {
    id: 36,
    nombre: "Clase de coctelería sin alcohol",
    descripcion: "Una clase o tutorial para preparar mocktails creativos, ideal para un grupo mixto o que prefiere no beber alcohol.",
    categoria: "amigos",
    tipo: "actividad",
    ocasion: "celebracion",
    presupuesto: "medio",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: "3-5",
    materiales: ["Frutas y jarabes", "Hielo", "Vasos y coctelera", "Recetas elegidas"],
    instrucciones: [
      "Elijan 2 o 3 recetas de mocktails para preparar.",
      "Compren los ingredientes frescos el mismo día.",
      "Túrnense para preparar cada receta entre todos.",
      "Voten cuál fue el mocktail favorito del grupo."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20mocktails%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=mocktails%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/mocktails/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-02-16",
    vistas: 231
  },
  {
    id: 37,
    nombre: "Concurso de disfraces temático",
    descripcion: "Una reunión con un tema definido donde todos llegan disfrazados y se premia el mejor look del grupo.",
    categoria: "amigos",
    tipo: "juego",
    ocasion: "celebracion",
    presupuesto: "economico",
    duracion: "todo el día",
    tiempo: "todo-el-dia",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Disfraces según el tema elegido", "Decoración temática", "Premio simbólico"],
    instrucciones: [
      "Elijan un tema de disfraces entre todos con anticipación.",
      "Decoren el espacio siguiendo esa misma temática.",
      "Al llegar, hagan una pequeña pasarela o presentación.",
      "Voten en grupo el disfraz más creativo."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=fiesta%20de%20disfraces%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=fiesta%20de%20disfraces",
    instagram: "https://www.instagram.com/explore/tags/fiestadedisfraces/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-05-25",
    vistas: 267
  },
  {
    id: 38,
    nombre: "Picnic grupal en el parque",
    descripcion: "Un picnic grande en el parque con juegos, comida compartida y música, ideal para un grupo numeroso.",
    categoria: "amigos",
    tipo: "salida",
    ocasion: "reunion",
    presupuesto: "gratis",
    duracion: "medio día",
    tiempo: "medio-dia",
    dificultad: "facil",
    personas: "6-10",
    materiales: ["Mantas", "Comida para compartir", "Juegos de patio", "Bocina"],
    instrucciones: [
      "Elijan un parque con sombra y espacio suficiente.",
      "Repartan qué lleva cada quien para la comida compartida.",
      "Lleven algún juego de patio para animar la tarde.",
      "Recojan todo antes de irse, dejando el lugar limpio."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=picnic%20grupal%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=picnic%20grupal",
    instagram: "https://www.instagram.com/explore/tags/picnicgrupal/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-04-27",
    vistas: 298
  },
  {
    id: 39,
    nombre: "Regalo sorpresa colectivo",
    descripcion: "El grupo se organiza en secreto para sorprender a alguien especial con un regalo o gesto colectivo.",
    categoria: "amigos",
    tipo: "regalo",
    ocasion: "dia-especial",
    presupuesto: "medio",
    duracion: "1 hora",
    tiempo: "menos-1h",
    dificultad: "facil",
    personas: "3-5",
    materiales: ["Fondo grupal", "Plan de entrega sorpresa"],
    instrucciones: [
      "Coordinen todo en un chat aparte, sin que la persona se entere.",
      "Definan el regalo o gesto y quién se encarga de cada parte.",
      "Planeen el momento y lugar de la sorpresa.",
      "Documenten la reacción para el recuerdo del grupo."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=sorpresa%20grupal%20de%20amigos",
    tiktok: "https://www.tiktok.com/search?q=sorpresa%20grupal%20amigos",
    instagram: "https://www.instagram.com/explore/tags/sorpresagrupal/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-03-30",
    vistas: 176
  },
  {
    id: 40,
    nombre: "Noche de stand-up comedy casero",
    descripcion: "Cada quien prepara una mini rutina de chistes o anécdotas graciosas para presentar frente al grupo.",
    categoria: "amigos",
    tipo: "experiencia",
    ocasion: "sin-ocasion",
    presupuesto: "gratis",
    duracion: "2 horas",
    tiempo: "1-2h",
    dificultad: "intermedia",
    personas: "3-5",
    materiales: ["Espacio con sillas en semicírculo", "Notas con ideas (opcional)"],
    instrucciones: [
      "Cada quien prepara una rutina corta de 2 a 3 minutos.",
      "Definan el orden de participación entre todos.",
      "Presenten por turnos frente al resto del grupo.",
      "Cierren votando el momento más divertido de la noche."
    ],
    pinterest: "https://www.pinterest.com/search/pins/?q=noche%20de%20comedia%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=stand%20up%20casero",
    instagram: "https://www.instagram.com/explore/tags/standupcasero/",
    estado: "aprobada",
    autor: "Equipo Juntos",
    fecha: "2026-06-06",
    vistas: 142
  },
  {
    id: 61,
    nombre: "Torneo de ping pong",
    descripcion: "Un torneo casero de ping pong con eliminatorias, ideal para una tarde competitiva sin gastar de más.",
    categoria: "amigos", tipo: "juego", ocasion: "celebracion", presupuesto: "economico",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: "3-5",
    materiales: ["Mesa de ping pong", "Paletas y pelotas"],
    instrucciones: ["Armen un cuadro de enfrentamientos.", "Jueguen partidos cortos para que todos participen varias veces.", "Lleven el marcador en una pizarra visible.", "Premien al ganador con algo simbólico."],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20de%20ping%20pong%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=torneo%20de%20ping%20pong",
    instagram: "https://www.instagram.com/explore/tags/pingpongconamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-14", vistas: 187
  },
  {
    id: 62,
    nombre: "Salida a un parque de diversiones",
    descripcion: "Un día completo en un parque de diversiones, subiéndose a los juegos favoritos del grupo.",
    categoria: "amigos", tipo: "salida", ocasion: "celebracion", presupuesto: "alto",
    duracion: "todo el día", tiempo: "todo-el-dia", dificultad: "facil", personas: "6-10",
    materiales: ["Entradas", "Efectivo o tarjeta para comida"],
    instrucciones: ["Compren las entradas con anticipación si hay descuento.", "Definan juntos un punto de encuentro por si se separan.", "Prioricen los juegos que más quieren repetir.", "Cierren el día con algo de comer todos juntos."],
    pinterest: "https://www.pinterest.com/search/pins/?q=parque%20de%20diversiones%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=parque%20de%20diversiones%20amigos",
    instagram: "https://www.instagram.com/explore/tags/parquedediversiones/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-21", vistas: 298
  },
  {
    id: 63,
    nombre: "Clase de improvisación teatral",
    descripcion: "Una clase o taller de improvisación donde el grupo juega dinámicas de actuación espontánea.",
    categoria: "amigos", tipo: "actividad", ocasion: "reunion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "6-10",
    materiales: ["Reserva del taller", "Ropa cómoda"],
    instrucciones: ["Busquen un taller de impro para grupos.", "Lleguen con mente abierta, sin miedo a hacer el ridículo.", "Participen en las dinámicas propuestas por el instructor.", "Cierren comentando los mejores momentos entre todos."],
    pinterest: "https://www.pinterest.com/search/pins/?q=improvisacion%20teatral%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=improvisacion%20teatral",
    instagram: "https://www.instagram.com/explore/tags/improteatral/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-19", vistas: 156
  },
  {
    id: 64,
    nombre: "Noche de fondue y juegos de mesa",
    descripcion: "Una noche relajada combinando fondue de queso o chocolate con una ronda de juegos de mesa.",
    categoria: "amigos", tipo: "reunion", ocasion: "sin-ocasion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: "3-5",
    materiales: ["Set de fondue", "Ingredientes (queso, chocolate, pan, fruta)", "Juegos de mesa"],
    instrucciones: ["Preparen el fondue según la receta elegida.", "Corten los ingredientes para mojar con anticipación.", "Coman mientras juegan una partida ligera.", "Repitan turnos de fondue entre partida y partida."],
    pinterest: "https://www.pinterest.com/search/pins/?q=noche%20de%20fondue%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=noche%20de%20fondue",
    instagram: "https://www.instagram.com/explore/tags/nochedefondue/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-05-09", vistas: 201
  },
  {
    id: 65,
    nombre: "Recorrido en bicicleta grupal",
    descripcion: "Una salida en bicicleta por una ruta segura de la ciudad o un parque, a un ritmo cómodo para todo el grupo.",
    categoria: "amigos", tipo: "salida", ocasion: "dia-especial", presupuesto: "gratis",
    duracion: "medio día", tiempo: "medio-dia", dificultad: "intermedia", personas: "6-10",
    materiales: ["Bicicletas", "Casco", "Agua"],
    instrucciones: ["Elijan una ruta apta para todos los niveles.", "Revisen que las bicicletas estén en buen estado antes de salir.", "Mantengan un ritmo cómodo para el más lento del grupo.", "Paren a mitad de camino para descansar e hidratarse."],
    pinterest: "https://www.pinterest.com/search/pins/?q=recorrido%20en%20bicicleta%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=bicicleta%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/bicicletaconamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-12", vistas: 223
  },
  {
    id: 66,
    nombre: "Torneo de cartas sin dinero",
    descripcion: "Una tarde de cartas (uno, póker con fichas, truco) jugando solo por diversión, sin apuestas reales.",
    categoria: "amigos", tipo: "juego", ocasion: "reunion", presupuesto: "gratis",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: "3-5",
    materiales: ["Mazo de cartas", "Fichas o botones para apostar"],
    instrucciones: ["Elijan el juego de cartas entre todos.", "Repartan fichas simbólicas para las apuestas.", "Jueguen varias rondas llevando el conteo.", "El ganador de la noche elige el próximo juego."],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20de%20cartas%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=torneo%20de%20cartas",
    instagram: "https://www.instagram.com/explore/tags/torneodecartas/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-21", vistas: 164
  },
  {
    id: 67,
    nombre: "Clase grupal de velas o jabones",
    descripcion: "Un taller creativo donde el grupo aprende a hacer sus propias velas o jabones artesanales.",
    categoria: "amigos", tipo: "actividad", ocasion: "celebracion", presupuesto: "economico",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "3-5",
    materiales: ["Cera o base de jabón", "Esencias y moldes", "Mandil"],
    instrucciones: ["Consigan los materiales o reserven un taller guiado.", "Repartan las estaciones de trabajo entre el grupo.", "Sigan los pasos de derretido y moldeado con cuidado.", "Lleven cada uno su creación a casa."],
    pinterest: "https://www.pinterest.com/search/pins/?q=taller%20de%20velas%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=taller%20de%20jabones%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/tallerdevelas/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-05", vistas: 148
  },
  {
    id: 68,
    nombre: "Salida a un museo o exposición",
    descripcion: "Una visita grupal a un museo, galería o exposición temporal, seguida de un café para comentar lo visto.",
    categoria: "amigos", tipo: "salida", ocasion: "dia-especial", presupuesto: "economico",
    duracion: "medio día", tiempo: "medio-dia", dificultad: "facil", personas: "6-10",
    materiales: ["Entradas", "Efectivo para el café después"],
    instrucciones: ["Revisen qué exposiciones hay disponibles ese mes.", "Compren entradas con descuento grupal si existe.", "Recorran a su propio ritmo, sin apurar a nadie.", "Terminen con un café comentando lo que más les gustó."],
    pinterest: "https://www.pinterest.com/search/pins/?q=visita%20a%20un%20museo%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=museo%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/museoconamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-27", vistas: 132
  },
  {
    id: 69,
    nombre: "Noche de misterio para resolver",
    descripcion: "Un juego de misterio tipo 'asesinato ficticio' donde cada quien tiene un personaje y pistas para resolver el caso entre todos.",
    categoria: "amigos", tipo: "juego", ocasion: "celebracion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "6-10",
    materiales: ["Kit de juego de misterio (impreso o comprado)", "Disfraces simples opcionales"],
    instrucciones: ["Consigan un kit de juego de misterio para el número de invitados.", "Repartan los personajes y pistas antes de empezar.", "Jueguen las rondas siguiendo las instrucciones del kit.", "Revelen al final quién era el culpable."],
    pinterest: "https://www.pinterest.com/search/pins/?q=juego%20de%20misterio%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=juego%20de%20misterio%20amigos",
    instagram: "https://www.instagram.com/explore/tags/juegodemisterio/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-06-18", vistas: 219
  },
  {
    id: 70,
    nombre: "Torneo deportivo entre amigos",
    descripcion: "Un partido o torneo de fútbol, básquet u otro deporte, organizado entre el grupo de amigos.",
    categoria: "amigos", tipo: "actividad", ocasion: "celebracion", presupuesto: "gratis",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: "mas-10",
    materiales: ["Balón", "Cancha o espacio disponible", "Agua"],
    instrucciones: ["Reserven o busquen una cancha disponible.", "Formen equipos parejos entre todos.", "Jueguen por tiempo o por puntos definidos antes de empezar.", "Cierren con algo de comer o beber entre todos."],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20deportivo%20entre%20amigos",
    tiktok: "https://www.tiktok.com/search?q=torneo%20deportivo%20amigos",
    instagram: "https://www.instagram.com/explore/tags/torneodeportivo/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-25", vistas: 276
  },
  {
    id: 71,
    nombre: "Amigo secreto sorpresa",
    descripcion: "Un intercambio de regalos tipo amigo secreto, con presupuesto definido y revelado en una reunión especial.",
    categoria: "amigos", tipo: "regalo", ocasion: "celebracion", presupuesto: "economico",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: "6-10",
    materiales: ["Papelitos para el sorteo", "Presupuesto definido por persona"],
    instrucciones: ["Sorteen los nombres sin que se sepa quién le tocó a quién.", "Definan un presupuesto máximo por regalo.", "Envuelvan los regalos sin identificarlos por fuera.", "Revélenlos todos juntos en la reunión."],
    pinterest: "https://www.pinterest.com/search/pins/?q=amigo%20secreto%20entre%20amigos",
    tiktok: "https://www.tiktok.com/search?q=amigo%20secreto",
    instagram: "https://www.instagram.com/explore/tags/amigosecreto/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-08", vistas: 341
  },
  {
    id: 72,
    nombre: "Clase de cocina grupal",
    descripcion: "Una clase donde el grupo aprende a preparar un platillo nuevo juntos, repartiéndose las tareas de la receta.",
    categoria: "amigos", tipo: "actividad", ocasion: "reunion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "3-5",
    materiales: ["Ingredientes de la receta", "Delantales"],
    instrucciones: ["Elijan una receta que todos quieran aprender.", "Repartan las tareas: cortar, mezclar, cocinar.", "Sigan la receta paso a paso en equipo.", "Coman juntos lo que prepararon."],
    pinterest: "https://www.pinterest.com/search/pins/?q=clase%20de%20cocina%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=clase%20de%20cocina%20amigos",
    instagram: "https://www.instagram.com/explore/tags/clasedecocina/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-13", vistas: 187
  },
  {
    id: 73,
    nombre: "Salida a un lago o playa cercana",
    descripcion: "Un día completo en un lago o playa cercana, con juegos de agua, comida compartida y buena música.",
    categoria: "amigos", tipo: "salida", ocasion: "dia-especial", presupuesto: "economico",
    duracion: "todo el día", tiempo: "todo-el-dia", dificultad: "facil", personas: "6-10",
    materiales: ["Traje de baño", "Protector solar", "Comida y bebidas"],
    instrucciones: ["Elijan un lago o playa accesible en un día.", "Repartan qué lleva cada quien para comer.", "Lleven juegos de playa o agua para animar el día.", "Salgan temprano para aprovechar más horas de luz."],
    pinterest: "https://www.pinterest.com/search/pins/?q=dia%20de%20playa%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=dia%20de%20playa%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/diadeplaya/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-06-01", vistas: 305
  },
  {
    id: 74,
    nombre: "Noche de karaoke en un bar",
    descripcion: "Salir a un bar con karaoke para cantar frente a los demás, en un ambiente más animado que en casa.",
    categoria: "amigos", tipo: "experiencia", ocasion: "celebracion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "facil", personas: "6-10",
    materiales: ["Reserva de mesa (opcional)", "Efectivo o tarjeta"],
    instrucciones: ["Busquen un bar con karaoke bien valorado.", "Anoten sus canciones apenas lleguen, suele haber turno.", "Anímense a cantar aunque no sean expertos.", "Apoyen y aplaudan a todos por igual."],
    pinterest: "https://www.pinterest.com/search/pins/?q=karaoke%20en%20un%20bar%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=karaoke%20en%20un%20bar",
    instagram: "https://www.instagram.com/explore/tags/karaokebar/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-05", vistas: 258
  },
  {
    id: 75,
    nombre: "Torneo de ajedrez relámpago",
    descripcion: "Un torneo de ajedrez con partidas rápidas (blitz), ideal para un grupo con jugadores de distinto nivel.",
    categoria: "amigos", tipo: "juego", ocasion: "reunion", presupuesto: "gratis",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "intermedia", personas: "3-5",
    materiales: ["Tableros de ajedrez", "Reloj de ajedrez (opcional)"],
    instrucciones: ["Definan el tiempo por partida (blitz de 3 o 5 minutos).", "Armen un cuadro de eliminación simple.", "Jueguen las rondas llevando el resultado.", "El ganador elige el próximo juego de la reunión."],
    pinterest: "https://www.pinterest.com/search/pins/?q=torneo%20de%20ajedrez%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=torneo%20de%20ajedrez",
    instagram: "https://www.instagram.com/explore/tags/torneodeajedrez/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-01-17", vistas: 121
  },
  {
    id: 76,
    nombre: "Grabar un video o podcast grupal",
    descripcion: "Grabar juntos un video divertido o un episodio de podcast casero, solo por diversión y para tener el recuerdo.",
    categoria: "amigos", tipo: "experiencia", ocasion: "sin-ocasion", presupuesto: "gratis",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "3-5",
    materiales: ["Celular o cámara", "Guion o temas a tratar (opcional)"],
    instrucciones: ["Definan el formato: video, reto o podcast conversado.", "Preparen un par de temas o ideas para no quedarse sin qué decir.", "Graben varias tomas sin presionarse por la perfección.", "Vean o escuchen el resultado juntos al final."],
    pinterest: "https://www.pinterest.com/search/pins/?q=video%20grupal%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=podcast%20casero%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/podcastconamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-04-08", vistas: 173
  },
  {
    id: 77,
    nombre: "Recorrido gastronómico por un mercado",
    descripcion: "Un paseo por un mercado local probando distintos puestos de comida, como plan económico y sabroso.",
    categoria: "amigos", tipo: "salida", ocasion: "reunion", presupuesto: "economico",
    duracion: "medio día", tiempo: "medio-dia", dificultad: "facil", personas: "3-5",
    materiales: ["Efectivo", "Ropa cómoda para caminar"],
    instrucciones: ["Investiguen qué mercado local tiene mejor variedad.", "Definan un presupuesto aproximado para repartir entre puestos.", "Prueben porciones pequeñas de varios lugares.", "Elijan juntos su plato favorito del recorrido."],
    pinterest: "https://www.pinterest.com/search/pins/?q=recorrido%20por%20un%20mercado%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=mercado%20gastronomico%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/mercadogastronomico/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-05-21", vistas: 196
  },
  {
    id: 78,
    nombre: "Clase grupal de escalada",
    descripcion: "Una clase introductoria de escalada en rocódromo, ideal para un grupo que busca un plan activo y distinto.",
    categoria: "amigos", tipo: "actividad", ocasion: "celebracion", presupuesto: "medio",
    duracion: "2 horas", tiempo: "1-2h", dificultad: "intermedia", personas: "3-5",
    materiales: ["Reserva del rocódromo", "Ropa deportiva"],
    instrucciones: ["Reserven una clase introductoria para principiantes.", "Sigan las indicaciones de seguridad del instructor.", "Anímense por turnos, sin forzar a quien tenga vértigo.", "Celebren cada logro del grupo, por pequeño que sea."],
    pinterest: "https://www.pinterest.com/search/pins/?q=escalada%20en%20rocodromo%20con%20amigos",
    tiktok: "https://www.tiktok.com/search?q=rocodromo%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/rocodromo/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-03-29", vistas: 142
  },
  {
    id: 79,
    nombre: "Rifa o bingo entre amigos",
    descripcion: "Organizar una rifa o bingo casero con premios simbólicos, ideal para una reunión grande y animada.",
    categoria: "amigos", tipo: "juego", ocasion: "celebracion", presupuesto: "economico",
    duracion: "1 hora", tiempo: "menos-1h", dificultad: "facil", personas: "mas-10",
    materiales: ["Cartones de bingo o boletos de rifa", "Premios pequeños"],
    instrucciones: ["Preparen los cartones o boletos con anticipación.", "Consigan varios premios simbólicos para repartir.", "Canten los números o hagan el sorteo frente a todos.", "Entreguen los premios apenas se complete cada ronda."],
    pinterest: "https://www.pinterest.com/search/pins/?q=bingo%20entre%20amigos",
    tiktok: "https://www.tiktok.com/search?q=bingo%20con%20amigos",
    instagram: "https://www.instagram.com/explore/tags/bingoconamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-02-14", vistas: 165
  },
  {
    id: 80,
    nombre: "Reunión anual de toda la vida",
    descripcion: "Un encuentro anual fijo para reunir a los amigos de siempre, sin importar cuánto tiempo haya pasado.",
    categoria: "amigos", tipo: "reunion", ocasion: "dia-especial", presupuesto: "medio",
    duracion: "todo el día", tiempo: "todo-el-dia", dificultad: "facil", personas: "mas-10",
    materiales: ["Lugar de reunión", "Comida y bebida para compartir"],
    instrucciones: ["Elijan una fecha fija cada año, fácil de recordar.", "Turnense quién organiza el lugar cada vez.", "Dejen tiempo libre para ponerse al día sin apuros.", "Tomen una foto grupal como tradición del encuentro."],
    pinterest: "https://www.pinterest.com/search/pins/?q=reunion%20anual%20de%20amigos",
    tiktok: "https://www.tiktok.com/search?q=reunion%20de%20amigos%20de%20toda%20la%20vida",
    instagram: "https://www.instagram.com/explore/tags/reuniondeamigos/",
    estado: "aprobada", autor: "Equipo Juntos", fecha: "2026-07-04", vistas: 289
  }

];


/* ============================================================
   Estadísticas ficticias para el dashboard de administración.
   No se derivan de IDEAS_DATA porque representan datos que,
   en una versión con backend, vendrían de otras tablas
   (usuarios, planes creados por usuarios, etc).
   ============================================================ */
window.APP_STATS = {
  usuarios: 128,
  planesCreados: 342
};
